#+BEGIN_HTML
---
layout: post
keywords: 
description: 
title: vmware使用问题
categories: [vmware]
tags: [vmware]
group: archive
icon: globe
featured: false
---
#+END_HTML
* linux下vmware tools安装
#+BEGIN_SRC sh
mount /cdrom
cp /cdrom/vmware-linux-tools.tar.gz /tmp
cd /tmp
tar zxvf vmware-linux-tools.tar.gz
cd vmware-tools-distrib
./vmware-install.pl
#+END_SRC
* vmware中ubuntu虚拟机增加磁盘
本文主要介绍vmware为ubuntu虚拟机添加一块硬盘后，系统内挂载的过程。
#+BEGIN_SRC sh
root@wchunx:~# fdisk -l
...
#添加的10G新硬盘，尚未分区
Disk /dev/sdc: 10.7 GB, 10737418240 bytes
255 heads, 63 sectors/track, 1305 cylinders, total 20971520 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x00000000
 
Disk /dev/sdc doesn't contain a valid partition table
 
root@wchunx:~# fdisk /dev/sdc
#进入硬盘操作界面
Command (m for help): n #新建分区
Partition type:
   p   primary (0 primary, 0 extended, 4 free)
   e   extended
Select (default p): p #选择主分区
Partition number (1-4, default 1): 1  #分区号为1
First sector (2048-20971519, default 2048): #新分区起始的磁盘块数，默认
Using default value 2048
Last sector, +sectors or +size{K,M,G} (2048-20971519, default 20971519): #分区大小，默认使用全部硬盘
Using default value 20971519
 
Command (m for help): p #打印该磁盘分区列表，查看到已经创建好的分区
 
Disk /dev/sdc: 10.7 GB, 10737418240 bytes
107 heads, 17 sectors/track, 11529 cylinders, total 20971520 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x1b2fb711
 
   Device Boot      Start         End      Blocks   Id  System
/dev/sdc1            2048    20971519    10484736   83  Linux
 
Command (m for help): w #分区写入硬盘
The partition table has been altered!
 
Calling ioctl() to re-read partition table.
Syncing disks.
 
root@wchunx:~# mkfs.ext4 /dev/sdc1 #格式化硬盘为ext4文件系统
mke2fs 1.42 (29-Nov-2011)
Filesystem label=
OS type: Linux
Block size=4096 (log=2)
Fragment size=4096 (log=2)
Stride=0 blocks, Stripe width=0 blocks
655360 inodes, 2621184 blocks
131059 blocks (5.00%) reserved for the super user
First data block=0
Maximum filesystem blocks=2684354560
80 block groups
32768 blocks per group, 32768 fragments per group
8192 inodes per group
Superblock backups stored on blocks:
    32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632
 
Allocating group tables: done                           
Writing inode tables: done                           
Creating journal (32768 blocks): done
Writing superblocks and filesystem accounting information: done
#这时fdisk -l就可以看到新建的分区
#编辑/etc/fstab，写入/dev/sdc1   /data   ext4   defaults   0 0  将新分区挂在到/data目录。
#重启后df -h可以看到挂载的新分区
#+END_SRC
* windows下vmware合并多个vmdx
合并多个vmdx为一个用到vmware-diskmanager.exe.位于vmware的安装目录。 \\
我的vmware-diskmanager.exe位于D:\Tools目录，虚拟机位于D:\Iso\vmware\SUSE Linux Enterprise 11 64-bit目录下，该目录下会有多个形如SUSE Linux Enterprise 11 64-bit-s001.vmdx带编号的vmdx文件，还会有一个SUSE Linux Enterprise 11 64-bit.vmdx不带编号的vmdx文件。

打开命令提示符
#+BEGIN_SRC sh
D:\Iso\vmware\SUSE Linux Enterprise 11 64-bit>D:\Tools\vmware-vdiskmanager.exe -
r "SUSE Linux Enterprise 11 64-bit.vmdk" -t 0 "SUSE 11.vmdk"
Creating disk 'SUSE 11.vmdk'
  Convert: 100% done.
Virtual disk conversion successful.
#+END_SRC
生成SUSE 11.vmdx。
* VMWare安装Ubuntu 12.04开启虚拟机的Unity Mode模式
主机操作系统是Windows 7 ,安装VMWare 9.0.2，虚拟机中运行Ubuntu 12.04 。当试图把VMWare切换到Unity Mode,我得到以下信息:

The virtual machine cannot enter Unity mode because: \\
- Unity is not supported on the guest operating system.

问题原因：VMWare和Ubuntu都有Unitiy，前者指的是Unity Mode，后者指的是Unity Shell。
** 解决办法：安装gnome
终端中输入：
#+BEGIN_SRC sh
sudo add-apt-repository ppa:gnome3-team/gnome3
sudo apt-get update
sudo apt-get install gnome-shell
#+END_SRC
更新完成后，注销，选择 Gnome Classic – No Effects桌面,进入系统即可。
* ubuntu12.04.2卸载VMware
在Ubuntu12.04.2上安装了VMware9.0.0后，总有问题。可能是9.0.0版本与3.5的内核有冲突。想要卸载

使用vmware-installer –uninstall-product vmware-workstation命令出现下面问题
#+BEGIN_SRC sh
The vmware installer could not shut down all running virtual machines. if you have ACE VMs open, please shut them down or suspend them now and press ‘Retry’ to continue.
#+END_SRC
最后解决办法 rm /etc/rc{2,3,4,5}.d/*vmware*删除VMware的开机启动脚本，然后重启机器，再运行上面的卸载命令成功卸载。

安装VMware-workstation9.0.2没有问题
** 参考资料
[[http://askubuntu.com/questions/155466/cant-uninstall-vmware-player-4-0-3][Can't uninstall Vmware player 4.0.3]]

[[http://forum.ubuntu-fr.org/viewtopic.php?id=1078441][Workstation 9 crash depuis mise a jour Ubuntu]]
