#+BEGIN_HTML
---
layout: post
keywords: 
description: 
title: Emacs24.3.1安装cedet和ecb
categories: [Emacs]
tags: [Emacs]
group: archive
icon: compass
featured: false
---
#+END_HTML
* Emacs24.3.1安装cedet和ecb
将Emacs23升级到Emacs24.3.1后，重新安装了cedet和ecb，记录在案。
** 安装cedet
到[[http://sourceforge.net/projects/cedet/?source=dlp][sourceforge]] 下载cedet-1.1.tar.gz,解压到.emacs.d/plugins/目录，make一下就ok了。
** 安装ecb
安装ecb的过程就麻烦一下。

1.同样到[[http://sourceforge.net/projects/ecb/?source=directory][sourceforge]] 下载ecb-2.4.0.tar.gz,解压到.emacs.d/plugins/目录。

2.make报错
#+BEGIN_SRC sh
Byte-compiling ECB with LOADPATH= ...
emacs -batch -no-site-file -l ecb-compile-script --eval '(ecb-byte-compile t)'
Cannot open load file: /home/latelee/.emacs.d/ecb-2.40/c:/Programme/emacs-22.3/site-lisp/package-development/cedet/common/cedet.el
make: *** [ecb] 错误 255
#+END_SRC
ecb依赖于cedet的,修改Makefile文件，51行CEDET=这一行，它的默认路径不是我们安装cedet的路径，

修改为实际cedet的路径。CEDET=~/.emacs.d/plugins/cedet-1.1

再make报错
#+BEGIN_SRC sh
Error: ECB can only be used with cedet [1.0pre6, 1.0.9]! Please install it and restart Emacs!
#+END_SRC
最新的ecb-2.40只兼容cedet版本 1.0.6pre ~ 1.0.9，解决的方法是修改/path/to/ecb-2.40/ecb-upgrade.el，将1146行的

(defconst ecb-required-cedet-version-max '(1 0 4 9))

改为

(defconst ecb-required-cedet-version-max '(1 1 4 9))

再make，成功
** xcscope的安装
xcscope沿用了Emacs23的xcscope.el,yasnippet直接从ELPA安装即可。
** yasnippet和auto-complete的安装
从ELPA下在的yasnippet版本0.8.0，auto-complete为1.4，使用发现还是冲突的，所以我还是沿用了之前Emacs23中的配置

用到的插件
[[http://github.com/capitaomorte/yasnippet][yasnippet]]
[[https://github.com/m2ym/auto-complete.git][auto-complete]]
[[https://github.com/m2ym/popup-el.git][popup]]
[[https://github.com/m2ym/fuzzy-el.git][fuzzy]]
[[https://github.com/winterTTr/emacs-of-winterTTr/blob/master/.emacs.d/plugins/auto-complete-suite/pos-tip/pos-tip.el][pos-tip]]

** 配置
下面代码加入.emacs
#+BEGIN_SRC elisp
;cedet
(load-file "~/.emacs.d/plugins/cedet-1.1/common/cedet.el")

;ecb
(add-to-list 'load-path "~/.emacs.d/plugins/ecb-2.40")
(require 'ecb)
(setq stack-trace-on-error nil)
;鼠标支持：Emacs中执行“M-x ecb-customize-most-important”，找到“Ecb Primary Secondary Mouse Buttons”选项，将其设为“Primary: mouse-1, secondary: mouse-2”，并且>以“Save for Future Sessions”保存。
;;;自动启动ecb
;; (setq ecb-auto-activate t)
;;;F7:打开ecb
(global-set-key  [(f7)] 'ecb-activate)
;;;F8:关闭ecb
(global-set-key  [(f8)] 'ecb-deactivate)
;关闭ecb启动窗口
(setq ecb-tip-of-the-day nil)

;安装cscope apt-get install cscope									 
;cscope
(load-file "~/.emacs.d/plugins/xcscope.el")
(require 'xcscope)
(setq cscope-do-not-update-database t)

;yasnippet
(add-to-list 'load-path
             "~/.emacs.d/plugins/yasnippet")
(require 'yasnippet)
(yas-global-mode 1)

(add-to-list 'load-path
             "~/.emacs.d/plugins/pos-tip")
(add-to-list 'load-path
             "~/.emacs.d/plugins/fuzzy-el")
(add-to-list 'load-path
             "~/.emacs.d/plugins/popup-el")
(add-to-list 'load-path
             "~/.emacs.d/plugins/auto-complete")

;加载auto-complete及内置模版
(require 'auto-complete-config)
(add-to-list 'ac-dictionary-directories
        "~/.emacs.d/plugins/auto-complete/dict")
(ac-config-default)

;quick-help,默认就是打开的
;(setq ac-use-quick-help t)
;(setq ac-quick-help-delay 1.0)

;使用增强popup列表,pos-tip模式
(require 'pos-tip)
(setq ac-quick-help-prefer-pos-tip t)   ;default is t

;关闭自动触发补全，定义TAB为触发键
(setq ac-auto-start nil)   ;auto complete using clang is CPU sensitive
(ac-set-trigger-key "<tab>")

;设置tab键的使用模式
(setq ac-dwim t)

;使用backspace后，ac补全就消失，设置backspace删除后仍可出发补全
(setq ac-trigger-commands
      (cons 'backward-delete-char-untabify ac-trigger-commands))

;fuzzy功能，输入错误信息也能模糊匹配
(setq ac-fuzzy-enable t)
#+END_SRC
** 参考资料
[[http://www.latelee.org/embedded-linux/64-learning-elinux-4-my-emacs-i.htmlhttp://www.latelee.org/embedded-linux/64-learning-elinux-4-my-emacs-i.html][嵌入式之行(4)：我的emacs(上)]]

[[http://blog.csdn.net/winterttr/article/details/7524336][emacs中使用auto-complete的详细设置]]

[[http://www.cnblogs.com/coderzh/archive/2009/12/26/emacspythonide.html][Emacs中打造强大的Python IDE]]

[[http://emacser.com/auto-complete.htm][Emacs才是世界上最强大的IDE － 用auto-complete实现自动补全]]

[[http://backcomer.diandian.com/post/2013-03-11/40048253403][Emacs ecb配置小结]]
