#+BEGIN_HTML
---
layout: post
keywords: blog
description: blog
title: 搭建本地jekyll博客
categories: [learning, jekyll,org-mode]
tags: [jekyll]
group: archive
icon: globe
featured: true
---
#+END_HTML

#+OPTIONS: ^:{}
* 搭建本地jekyll博客
** 安装jekyll
#+BEGIN_SRC sh
#安装ruby
sudo apt-get install ruby1.9.1-dev
#在国内可能Ruby的Gem sources很慢，在install jekyll前可以执行下面两个命令
替换gem sources为淘宝的gem镜像。但我没有换，安装也是没问题的
gem sources -r http://rubygems.org/
gem sources -a http://ruby.taobao.org/
#安装jekyll
sudo gem install jekyll
#安装rdiscount
sudo gem install rdiscount
#查看jekyll版本
jekyll -v
jekyll 1.2.1
#+END_SRC
** 创建博客
1.可以直接使用jekyll命令创建一个简单的jekyll站点架构
#+BEGIN_EXAMPLE sh
jekyll new Myblog
cd Myblog
jekyll serve
#+END_EXAMPLE
启动了jekyll serve后直接在浏览器中访问http://localhost:4000 就可以看到效果了

2.还可以直接clone现成的jekyll框架如[[jekyllbootstrap.com][Jekyll-Bootstrap]]或[[http://octopress.org/][Octopress]]
#+BEGIN_EXAMPLE sh
git clone https://github.com/plusjade/jekyll-bootstrap.git
cd jekyll-bootstrap
jekyll serve
#+END_EXAMPLE
访问http://localhost:4000 查看。

在网上看到好的jekyll博客，就到github上搜索，直接clone下来，做些修改就可以用作自己的框架，
更可以学习。
* 用Emacs写jekyll博客
jekyll默认是将Markdown文档转换为静态网页，本身是不支持对org-mode的文件进行转换。但有一个
开源项目[[https://github.com/jsuper/org-jekyll-mode][org-jeky-mode]] 它可以将org文档自动转换为html并放到jekyll的_posts目录下。
** org-jekyll-mode介绍
org-jekyll-mode是一个emacs的插件，能够帮助用户使用org-mode来编写jekyll的博客文章,使用
org-jekyll-mode既可以快速创建类似jekyll博客文章命名格式的org-mode文件，也能够创建一个文
件名不带时间前缀的文件。

同时，org-jekyll-mode能够将最终导出的文件格式化成标准的jekyll博客文章格式。如果你创建的
org-mode文件的文件名是不带时间戳前缀的，那么org-jekyll-mode在导出最终的html文件之后，
会在输出文件的文件名之前自动加上时间戳，如果你在org-mode-file中设定了#+DATE:选项，那么最
终导出文件的时间戳则会以这个值为准，否则就采用当前时间。同时，org-jekyll-mode也可以直接在
org-mode文件中控制最终导出文件的yaml font matter，目前包含了所有jekyll支持的yaml front
matter keywords。不过，如果需要在org-mode文件中使用的话，这些关键字前面都需要加上#+YAML/
前缀。同时keyword最好大写。
** org-jekyll-mode的使用方法
org-jekyll-mode使用非常简单，只需要将其最新的代码克隆到本机，在.emacs里面添加如下代码:
#+BEGIN_EXAMPLE Lisp
;org-jekyll
(add-to-list 'load-path "~/.emacs.d/plugins/org-jekyll-mode")
(require 'org-jekyll-mode)
(setq org-jekyll/jekyll-project-root "~/Myblog")
(setq org-jekyll/org-mode-project-root "~/Myblog/org")
#+END_EXAMPLE 
注意一些变量值的定义

*org-jekyll/jekyll-project-root*

这个变量指定了你的jekyll项目的根目录。因为org-jekyll-mode会根据这个路径，
将其文件发布到这个目录的相应子目录下。

*org-jekyll/org-mode-project-root*

该变量指定了你的org-mode文件存放的目录。

*org-jekyll/org-mode-static-files-folder-name*

这个变量指定了你在org-mode项目目录下，用于存放静态文件，如：图片、css等文件的目录名。
默认是你的org-mode项目的根目录。
*** 发布当前文件
org文件编辑完后只需执行M-x org-jekyll/publish-project即完成发布。
*** 快捷键
*[C-c C-n]* 创建一个新的org-mode文件，但是其文件名并不会带上时间戳。如果需要将在某一个子目录
下创建该文件，只需要在目录名和文件名之间使用斜杠分开即可，如：2013/hello-world 就会在
org-mode-project-root下，如果没有2013目录，则创建，否则在2013目录下创建hello-world.org文件.

*[C-c C-d]* 功能跟C-c C-n一样，不过这个快捷键创建的文件会带上时间 戳，也就是标准的jekyll post文件名格式。

*[C-c C-p]* 发布当前文件
* 参考资料
[[http://www.soimort.org/posts/157/][soimort]]

[[http://www.zhanxin.info/jekyll/][Jekyll教程]]

[[http://www.cnblogs.com/waterlin/archive/2011/10/09/2203996.html][Org-mode标记语言的一些疑问]]

[[http://demi-panda.com/2012/10/30/install-jekyll/][Linux安装Jekyll环境]]

[[http://jsuper.github.io/posts/using-org-mode-to-write-jekyll-post.html][使用org-mode撰写jekyll博文]]

[[http://pieux.github.io/blog/2013-05-02-set-up-octopress-with-org-mode.html][Octopress搭配Org Mode写博客]]

[[http://wenshanren.org/?p=327][Emacs：在 org-mode 中插入源代码块]]

[[http://www.cnblogs.com/holbrook/archive/2012/04/12/2444992.html][Emacs学习笔记(9):org-mode，最好的文档编辑利器，没有之一]]
